# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app_name: '%env(APP_NAME)%'
    app_email_admin: '%env(APP_ADMIN_EMAIL)%'
    app_use_smtp: '%env(bool:APP_SEND_EMAILS)%'
    app_email_from:
        name: '%env(APP_EMAIL_FROM_NAME)%'
        email: '%env(APP_EMAIL_FROM_EMAIL)%'
    app_email_reply_to:
        name: '%env(APP_EMAIL_REPLY_TO_NAME)%'
        email: '%env(APP_EMAIL_REPLY_TO_EMAIL)%'
    env(APP_EMAIL_REPLY_TO_NAME): '%env(APP_EMAIL_FROM_NAME)%'
    env(APP_EMAIL_REPLY_TO_EMAIL): '%env(APP_EMAIL_FROM_EMAIL)%'
    app_default_poll_duration: '%env(int:APP_DEFAULT_POLL_DURATION)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Framadate\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Framadate\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Framadate\Services\MailService:
        arguments:
          - '@session'
          - '@mailer'
          - '@logger'
          - '@translator'
          - '%env(APP_SEND_EMAILS)%'
          - '%app_name%'
          - '%app_email_from%'
          - '%app_email_reply_to%'

    Framadate\Form\ArchiveType:
        arguments:
            - '%app_default_poll_duration%'
